// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "Launcher": {
      /**
       * GetApps
       * @returns {Promise<Array<App>>}  - Go Type: []main.App
       */
      "GetApps": () => {
        return window.go.main.Launcher.GetApps();
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.Launcher.Greet(arg1);
      },
    },
  },

};
export default go;
