// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "Launcher": {
      /**
       * Delete
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "Delete": (arg1) => {
        return window.go.main.Launcher.Delete(arg1);
      },
      /**
       * Download
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "Download": (arg1) => {
        return window.go.main.Launcher.Download(arg1);
      },
      /**
       * GetApps
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetApps": () => {
        return window.go.main.Launcher.GetApps();
      },
      /**
       * Play
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "Play": (arg1) => {
        return window.go.main.Launcher.Play(arg1);
      },
    },
  },

};
export default go;
